### ISSUE TITLE
Impersonating newly created user doesn't work

### ISSUE THREAD

**Issue by simonspa** [nextcloud/impersonate#40]
When trying to impersonate a new user directly after its creation (no login ever from this user) the impersonation does not work. Instead, the current user (administrator) is impersonated, i.e. I have a nested login `admin -> admin`

How to reproduce: 

* Enter user name and password, click "create" to get a new user
* Immediately click on "impersonate"

Expected: impersonation of new user
Actual behavior: impersonation of currently logged in user

This is Impersonate 1.0.3 on Nextcloud 13.0.1, running on Debian 9, PHP7.1 and nginx.

**Comment by theopen-institute** [comment]
I have been running into this too, though I think the issue is not with the impersonate plugin but with the core nextcloud codebase. Specifically, it seems that some parts of the new user creation process only happen when the user first logs in, so the account doesn't fully exist until then. This isn't just a problem for impersonate but for other applications as well.

**Comment by Dubidubiduu** [comment]
So, in between you changed behaviour, so it's not longer possible to impersonate a never logged in user. I guess it's not that easy to run the first-login-subroutine when neccessary?

**Comment by blizzz** [comment]
> So, in between you changed behaviour, so it's not longer possible to impersonate a never logged in user. I guess it's not that easy to run the first-login-subroutine when neccessary?

Correct.
