### ISSUE TITLE
Not working with Nextcloud 14.03

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/impersonate#59]
Just thought I should let ya'll know.

**Comment by blizzz** [comment]
@jcklpe sorry, this is not helpful at all. Please give a proper description: what you did, what you expected, what happened, logs.

**Comment by mscholl** [comment]
@blizzz Just experienced the same issue so let me give some more info on that:

I just upgraded from 13.0.6 to 14.0.3 and I was informed that the impersonate app was disabled due to incompatibility. If I look into the app section where I would in theory be able to upgrade impersonate app to 1.1.0 I am told that 

```
Diese App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:

    Server version 13 or lower is required.
```

which basically says "cannot install app because it requires Nextcloud 13 or lower". Impersonate app description, however, says that v1.1.0 would be compatible to Nextcloud 14. I assume that Nextcloud just does not understand the nextcloud dependency version string `>=14.0.0,<15.0.0` which can be found here https://apps.nextcloud.com/apps/impersonate/releases?platform=14#14.

**Affected Nextcloud version:** `14.0.3`
**Affected Impersonate version:** `1.1.0`

**Expected behavior:**

Ability to upgrade to impersonate app version 1.1.0 and use it

**Actual behavior:**

Impersonate app is disabled and cannot be upgraded due to incompatibility with Nextcloud version 14.0.3

If you need more info just let me know. Thanks

**Comment by mscholl** [comment]
Hm, just did some additional experiments and was able to upgrade although there where error notifications. I somehow managed to upgrade to 1.1.0 now and it works. Strange...

**Comment by blizzz** [comment]
Strange enough, as 14 is the only supported server version for 1.1.0:

![screenshot_20181016_193428](https://user-images.githubusercontent.com/2184312/47035511-7f7e5080-d17a-11e8-9478-1ee487b89cdb.png)

And if those checks would fail, a huge amount of apps would fail. That's common practice.

Perhaps it is just oddly cached… but I have not heard about such cases anywhere else. Could you try to remove and reinstall the app?

**Comment by jcklpe** [comment]
@blizzz  Apologies for the lack of detail. It seems that this is happening with a lot of apps after the upgrade to 14 and simply requires the app to be uninstalled and then reinstalled. I'll check back in if this doesn't work.
